name: Scheduled Playwright Tests
on:
  schedule:
    # Runs every day at 02:00 AM UTC
    - cron: '0 4 10 8 *'
  workflow_dispatch: # Allows manual trigger from the UI

permissions: 
    contents: write # Required for committing files to the repository / adding screenshots to a branch
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test/screenshot-more-than-one.spec.ts
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Commit Images to a public link branch
      if: always()
      run: |
        git config --global user.name "GitHub Automation Bot"
        git config --global user.email "actions@github.com"      
        # Switch to an isolated branch specifically for holding output image media assets
        git checkout -b media-storage || git checkout media-storage     
        # Add, commit and force-upload the new screenshot files
        git add screenshots/
        git commit -m "storage: append timestamped run images [skip ci]"
        git push origin media-storage --force
    
  
    
